INSERT IGNORE INTO skills (id, name, category) VALUES
(UUID_TO_BIN(UUID()), 'Spring Security', 'Security'),
(UUID_TO_BIN(UUID()), 'Hibernate', 'Backend'),
(UUID_TO_BIN(UUID()), 'Maven', 'Build'),
(UUID_TO_BIN(UUID()), 'Gradle', 'Build'),
(UUID_TO_BIN(UUID()), 'JavaScript', 'Frontend'),
(UUID_TO_BIN(UUID()), 'TypeScript', 'Frontend'),
(UUID_TO_BIN(UUID()), 'Vite', 'Frontend'),
(UUID_TO_BIN(UUID()), 'Node.js', 'Backend'),
(UUID_TO_BIN(UUID()), 'Python', 'Backend'),
(UUID_TO_BIN(UUID()), 'Go', 'Backend'),
(UUID_TO_BIN(UUID()), 'C#', 'Backend'),
(UUID_TO_BIN(UUID()), 'SQL', 'Data'),
(UUID_TO_BIN(UUID()), 'PostgreSQL', 'Data'),
(UUID_TO_BIN(UUID()), 'MongoDB', 'Data'),
(UUID_TO_BIN(UUID()), 'Redis', 'Data'),
(UUID_TO_BIN(UUID()), 'GraphQL', 'Backend'),
(UUID_TO_BIN(UUID()), 'OAuth 2.0', 'Security'),
(UUID_TO_BIN(UUID()), 'OpenID Connect', 'Security'),
(UUID_TO_BIN(UUID()), 'GitHub', 'Tooling'),
(UUID_TO_BIN(UUID()), 'Kubernetes', 'DevOps'),
(UUID_TO_BIN(UUID()), 'CI/CD', 'DevOps'),
(UUID_TO_BIN(UUID()), 'AWS', 'Cloud'),
(UUID_TO_BIN(UUID()), 'Azure', 'Cloud'),
(UUID_TO_BIN(UUID()), 'Terraform', 'DevOps'),
(UUID_TO_BIN(UUID()), 'Linux', 'DevOps'),
(UUID_TO_BIN(UUID()), 'Testing', 'Quality'),
(UUID_TO_BIN(UUID()), 'OpenAPI', 'Backend'),
(UUID_TO_BIN(UUID()), 'WebSockets', 'Backend'),
(UUID_TO_BIN(UUID()), 'Messaging', 'Backend');